### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by AKWB** [BU-ISCIII/iSkyLIMS#10]
Hi there,

are you planning to create a docker image in future?

Greets

**Comment by saramonzon** [comment]
Hi!
Yes! I will try to make it asap, this week or next one :)

**Comment by saramonzon** [comment]
By the way we have a problem with the release the other day, you can reclone the code now if you haven't done it!

**Comment by saramonzon** [comment]
Hello there!
We have just finished a singularity container, if you want to try this installation. Instructions can be found in the [README](README.md). We will provide a docker and singularity recipe in the near future too!

**Comment by AKWB** [comment]
I tried and after some clean up on my PC it works. Cool!
If I would like to modify something, e.g. a contact name or so, how can I do that? Or is it not at all possible to modify the code of iSkyLIMS in a container?

**Comment by saramonzon** [comment]
Hi Anke!
The container we provide is not writable, but I have created one writable for you. Also I have uploaded the virtual machine to drive for you to download! The writable container has "img" as file extension instead of "simg", you have to run or shell into it as sudo for making modifications in the code or whatever you want to modify.

Here you have the link to the drive folder: https://drive.google.com/open?id=1IIWjYSflTnj3L6mVAuRya0UsK-4lEig3

If you have any problem please ask!

**Comment by AKWB** [comment]
Thank you very much!!!!!!!

Gesendet: Montag, 06. Mai 2019 um 11:02 Uhr
Von: "Sara Monzón" <notifications@github.com>
An: BU-ISCIII/iSkyLIMS <iSkyLIMS@noreply.github.com>
Cc: AKWB <Anke.Wienecke@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [BU-ISCIII/iSkyLIMS] Docker container (#10)


Hi Anke!
The container we provide is not writable, but I have created one writable for you. Also I have uploaded the virtual machine to drive for you to download! The writable container has "img" as file extension instead of "simg", you have to run or shell into it as sudo for making modifications in the code or whatever you want to modify.

Here you have the link to the drive folder: https://drive.google.com/open?id=1IIWjYSflTnj3L6mVAuRya0UsK-4lEig3

If you have any problem please ask!

**Comment by iohenkies** [comment]
Hi! Any news on the Docker file?

The instructions for the singularity containers (both img and simg) don't work unfortunately. You can't start mysql.

`* Starting MariaDB database server mysqld                                     [fail]`

I would prefer a Dockerfile/container and am wondering what the status is.

**Comment by iohenkies** [comment]
I've created this. Maybe it is of use to others:
https://github.com/iohenkies/iskylims_docker

**Comment by saramonzon** [comment]
Wow!! Thank you very much! Sorry for the late response I was trying to figured out how to make the time for this! 
This is awesome thanks!! We will include this in the documentation asap! :)
