### ISSUE TITLE
new parameter for protocol that already has records in the LibParametersValues, fails to display sample information

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#102]
When we add a new parameter for a protocol that already has records in the LibParametersValues table, it fails to display the sample information because that parameter does not exist for all samples.

Parameters Configuration/Create new protocol/ Protocols already defined for Library Preparations select the protocol and Modify Protocol Fields

**Comment by luissian** [comment]
Issue solved in commit 3f20835a92db1e4ff6023047a7fba25d300a8afd
