### ISSUE TITLE
Search services working as search runs with the sharing option

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#103]
If I have shared my runs with an user, that user should be able to check my services besides my runs.

**Comment by luissian** [comment]
The shared runs is now allowed in wetlab and drylab
- On Wetlab
    -    Display result included runs shared by allowed users on commit e5ed28b3e5ecdfb942b0a97bb338061d44fc344a
    -   Allow display the run of the shared user on commit e5ed28b3e5ecdfb942b0a97bb338061d44fc344a
    -   Allow to search and display the project to shared users in commit  acc9c88b3fed14e41f08774ff05af5e430d3934f
- On Drylab already implemented in version 2.3.1
