### ISSUE TITLE
Where is the demo_iSkyLIMS.ova file?

### ISSUE THREAD

**Issue by masaomi** [BU-ISCIII/iSkyLIMS#11]
It is written as "After successful loging transfer the file demo_iSkyLIMS.ova which it is inside the iSkyLIMS folder." in the README, but I cannot find it. Please make a link to it.

Thanks,
Masa

**Comment by masaomi** [comment]
Sorry I missed it the description of FTP above it.

**Comment by saramonzon** [comment]
Hi! Yes it is in the ftp but I think there was a problem and it was not copied. Now it is available. 
It is a bit old version of iskylims but it will allow you to see the main functionality. We are working in a singularity/docker image too at the moment. 
Thanks for trying our tool!
