### ISSUE TITLE
La sección Unknown Barcodes en la página de un run no muestra correctamente los barcodes

### ISSUE THREAD

**Issue by Fabian-RY** [BU-ISCIII/iSkyLIMS#110]
Al entrar en la sección de Unknown barcodes aparece el mismo barcode repetido muchas veces
![Unknown_barcodes](https://user-images.githubusercontent.com/57529812/187227169-0727fdea-01f6-41da-9e67-69791b3810d2.png)

Al final del la página, el quesito muestra que solo hay un unknown barcode (cuyo valor corresponde a la suma de los valores que hay en la lista, cuando debía ser solo una vez)
![Unknown_barcodes2](https://user-images.githubusercontent.com/57529812/187227355-e707317a-ee2d-4497-8428-b415b26e3795.png)

Además, en el archivo ConversionStats.txt aparecen más barcodes de los que aparecen en la página. He adjuntado el archivo en el zip.

[ConversionStats.zip](https://github.com/BU-ISCIII/iSkyLIMS/files/9445451/ConversionStats.zip)

**Comment by luissian** [comment]
When saving the barcodes , only the last one per lane was saved.
This was because the creation action was outside of  the "for" statement, and must be inside

`                    RawTopUnknowBarcodes.objects.create_unknow_barcode(
                        unknow_barcode
                    )`
Bug is corrected in version 2.3.1
