### ISSUE TITLE
Demo data

### ISSUE THREAD

**Issue by mickaelleclercq** [BU-ISCIII/iskylims#111]
### Description of feature

Hi,
Is there any demo data available to play with iSkyLIMS and evaluate it ?

Thank you

**Comment by mickaelleclercq** [comment]
up

**Comment by luissian** [comment]
Hi Mickael.
There is not any demo data yet,  that you can load into iSkyLIMS.
We get your very value issue and we agree to have this data available, but it will take some time.

In the meantime if you want to know any point in particular we will happy to explain you in more detail.
I recommend  you to have a look to the documentation
https://iskylims.readthedocs.io/en/latest

**Comment by saramonzon** [comment]
Here we are! We have this demo data: https://zenodo.org/record/8059345

We are working on some docs along with some docker containers to create a proper testing environment. We'll close when this is set.

**Comment by saramonzon** [comment]
Done! we have a proper demo data in a docker compose configuration for testing and developing. More in [readme](./README)
