### ISSUE TITLE
Error looking for a service

### ISSUE THREAD

**Issue by Alema91** [BU-ISCIII/iSkyLIMS#113]
### Description of the bug

When the service SRVCNM657 is checked the next issue appears:

![image](https://user-images.githubusercontent.com/23449453/194528382-35317413-0a69-4d4f-a6ea-fcd93ff84687.png)

Thanks!

**Comment by luissian** [comment]
fixed in commit  5245c36e5863995a7b254b20d5f424baf70d8947
