### ISSUE TITLE
Display number of samples requested for a service

### ISSUE THREAD

**Issue by GuilleGorines** [BU-ISCIII/iSkyLIMS#114]
### Description of feature

It would be very handy if, inside of the "Samples in Service" tab in the service request, the number of samples involved was displayed. This would help check that all samples inside a service have been properly selected. Here is an example of the approximated idea I have in mind (I have censored all unrelated information)

![iSkyLIMS_request_sample_number](https://user-images.githubusercontent.com/60110848/196155666-27273530-1d01-4008-a529-049e344e471e.png)

Thank you!

**Comment by luissian** [comment]
implemented in commit b345c0278cc61693be5d067ec26cc5e074e3a54c
