### ISSUE TITLE
Can't record samples

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iSkyLIMS#115]
### Description of the bug

When trying to record samples sequenced outside, after filling the spreadsheet via web or uploading the spreadsheet.csv, iSkyLIMS will prompt an error.

I tried to write the date both via caldendar and pasting it manually.

### Relevant files

spread sheet example:
[spreadsheet_flu_one.csv](https://github.com/BU-ISCIII/iSkyLIMS/files/9937311/spreadsheet_flu_one.csv)

Error screenshot when generating spreedsheet online:
![Screenshot from 2022-11-04 11-32-13](https://user-images.githubusercontent.com/25959991/199952117-9e37d31a-5820-4d1e-ae86-93b88161e1d7.png)

Error uploading spreadsheet (template downloaded from web):
![Screenshot from 2022-11-04 11-33-58](https://user-images.githubusercontent.com/25959991/199952421-699264e5-2045-4d30-8f52-b106341e41df.png)

### System information

- iSkyLIMS version: 2.3.0 (https://iskylims.isciii.es/)
- Hardware: Desktop
- OS: Linyx

**Comment by luissian** [comment]
Already corrected in version 2.3.1
