### ISSUE TITLE
Problem when 2 resolution have the same availableservices selected

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#116]
https://github.com/BU-ISCIII/iSkyLIMS/blob/3d2cbbd44edd1b931d9d8cad6d5f1ea448c26ae8/iSkyLIMS_drylab/utils/handling_request_services.py#L544-L546

If two resolutions have the same services selected they are removed in the first resolution so it fails in the next resolution. We need to fix this. Two resolution may have the same services selected.

Trace error: 
[ValueError at _drylab_display_service=2310_.pdf](https://github.com/BU-ISCIII/iSkyLIMS/files/10066995/ValueError.at._drylab_display_service.2310_.pdf)

**Comment by luissian** [comment]
solved at PR #137
