### ISSUE TITLE
Firefox CSRF verificaiton error in the demo VM

### ISSUE THREAD

**Issue by masaomi** [BU-ISCIII/iSkyLIMS#13]
The demo VM worked but Firefox showed "CSRF verification failed". Do you know the simple solution to disable the CSRF verification in the demo VM?

Thanks for your help,
Masa

**Comment by saramonzon** [comment]
We will take a look and tell you something!

**Comment by luissian** [comment]
I will create a new VM with the latest version

**Comment by masaomi** [comment]
Thank you so much!!
While you are preparing, I try to install/setup iSkyLIMS in my environment.

**Comment by saramonzon** [comment]
Hi!
We are still working in the Virtual Machine, but you can already use a singularity container we have uploaded to our sftp. Instructions can be found in the repo [README](README.md).
Any problem please tell us!

**Comment by masaomi** [comment]
Thank you for the updating! I will check it and get feedback to you if I have a problem. Thanks.

**Comment by ray1919** [comment]
I encountered same error, and tried to use singularity container to test iSkyLIMS. 

However, neither iskylims.img or iskylims.simg works right. 

`service smbd start` return `* Starting SMB/CIFS daemon smbd                                                    [fail]`

 `service mysql start` return `/usr/sbin/mysqld: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 13 "Permission denied") Fatal error in defaults handling. Program aborted`

How should I do?

**Comment by luissian** [comment]
Hi ray1919
To start the services (smbd and mysql) you have to execute the container as root. 
Could you please check that your write "sudo" before singularity command?

sudo singularity shell iskylims.simg

Related to the VM and the   "CSRF verification failed".
Could you please tell me in which scenario you get it? 
Thanks
Luis

**Comment by seon22break** [comment]
Sorry, I'm a bit late, but the CSRF error, I have solved it by setting False in settings for the variable CSRF cookies privacy

**Comment by seon22break** [comment]
> The demo VM worked but Firefox showed "CSRF verification failed". Do you know the simple solution to disable the CSRF verification in the demo VM?
> 
> Thanks for your help,
> Masa
Sorry, I'm a bit late, but the CSRF error, I have solved it by setting False in settings for the variable CSRF cookies privacy

**Comment by seon22break** [comment]
> The demo VM worked but Firefox showed "CSRF verification failed". Do you know the simple solution to disable the CSRF verification in the demo VM?
> 
> Thanks for your help,
> Masa

Sorry, I'm a bit late, but the CSRF error, I have solved it by setting False in settings for the variable CSRF cookies privacy

**Comment by masaomi** [comment]
Thanks!!

**Comment by luissian** [comment]
VM will not longer available. 
Docker container is provided instead
