### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iskylims#131]
- [ ] Error handling:
There are heterogeneous ways when handling errors in the code. Some times raise exception is used and sometines only a return is used. We should change all of them to proper Exception defined clases. Proposal: 
Inside the function:
```
            try:
                project_sample_data["user_id"] = samples_with_user_ids[sample]
            except KeyError as e:
                raise KeyError(33)
```
Error handling in main function: 
```
try:
            process_and_store_samples_projects_data(sample_project_parsed_data, run_process_obj, experiment_name)
        except KeyError as key_error:
            string_message = experiment_name + ' : Error when processing and storing samples in projects.'
            logging_errors (string_message, True, False)
            if key_error.args[0] == 33:
                handling_errors_in_run (experiment_name, '33' )
            else:
                string_message = experiment_name + ' : Unknown error when processing and storing samples in projects.'
                logging_errors (string_message, True, False) 
            logger.debug('%s : End function manage_run_in_processed_bcl2fast2_run with error', experiment_name)
            continue
        except Exception as e:
            string_message = experiment_name + ' : Unknown error when processing and storing samples in projects.'
            logging_errors (string_message, True, False)
            continue
```
Maybe we could check if there it is known error in the database...or maybe there is another way. In any case we should check this way so we handle known and unknown errors and the code won't crush. We can talk about it.
- [ ] Use serializers for sending information to display to templates. Now custom and heterogeneous data structures are created and sent to templates so each method in view is different. We can use serializers that creates pre-configured jsons which are always the same making it easier to mantain with a huge reduce in code. Example in `display_service` in drylab.
- [ ] Explore using ajax, so we reduce the time of drawing large number of samples.
- [x] #133
- [ ] When a sample attribute (e.g. species) does not exist, there are many ways in the code to handle it:
in core/models.py line 1298:
```
        try:
            sample_info.append(self.species.get_name())
        except AttributeError:
            sample_info.append("Not defined")
```
But in line 1369:
```
    def get_species(self):
        if self.species is None:
            return "Not defined"
        else:
            return "%s" % (self.species.get_name())
```
And for date in line 1282:
```
        if self.collection_sample_date:
            collection_sample_date = self.collection_sample_date.strftime("%Y-%m-%d")
        else:
            collection_sample_date = ""
```

**Comment by luissian** [comment]
Not implemented changes in this issue are split in individual issues and moved to the release 3.2 at iSkyLIMS
