### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by GHKosovo** [BU-ISCIII/iSkyLIMS#14]
#I follow the Wiki Installation steps on github till Configuration
#when I execute the command "sudo su - django" below,
#reported
#"No directory, logging in with HOME=/
#mkdir: cannot create directory ‘//.cache’: Permission denied
#-su: 19: /etc/profile.d/wsl-integration.sh: cannot create #//.cache/wslu/integration: Directory nonexistent"
sudo su - django

cd /srv/iSkyLIMS
#when I execute soure virtualenv/bin/activate
#report the problem like this "-su: 2: source: not found"
source virtualenv/bin/activate

#so I will not continue to execute the following command
./manage.py crontab add 
# logout django user
exit

**Comment by luissian** [comment]
Hi GHKosovo.

Really sorry for the late response. 
It is crazy these days.

When writing "-" in the su command you read the user profile that is in their home directory. 
For executing the following commands there is not need to read your profile just only become djago user to activate the crontab.

replace the command by this without "-"
sudo su django

Thanks for your post, I have just corrected in the documentation
If you have any other issue please let us know, we will try to answer you earlier

**Comment by GHKosovo** [comment]
Thank you very much!
