### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by seon22break** [BU-ISCIII/iSkyLIMS#16]
I'm a little late and I don't know if work is still being serviced, but I would like to know how to fix the error in the photo.

From what I can deduce, it is an error since it does **not create the temporary file** and therefore cannot read it.  All files have full permissions. I am working with VM.
![Captura](https://user-images.githubusercontent.com/36485771/95220929-445a0980-07f7-11eb-8a03-e50dc4aecd73.PNG)

Thank you very much

**Comment by luissian** [comment]
I am really sorry for the very late response to you.
We will release a new version of iSkyLIMS soon. The VM for demo is not longer supported and removed from the FTP site.
Docker container is used for now on for people that want to test iSkyLIMS.

As mention stable release will be delivery in October 2021, but if you want to test the beta version, you can follow the instructions provided in the documentation site:
https://iskylims.readthedocs.io/en/latest/Installation.html
