### ISSUE TITLE
Problem in sequencerDetails

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iskylims#173]
### Description of the bug

http://localhost:8001/wetlab/sequencerDetails=2

![image](https://github.com/BU-ISCIII/iskylims/assets/3480206/df156d33-f3b0-490f-a0d8-8a4333fc9dec)

### Command used and terminal output

```console
http://localhost:8001/wetlab/sequencerDetails=2
```

**Comment by luissian** [comment]
solved in commit fdabd1bfdb20dbce9b4bb0d2ad824dcd9ffed277
