### ISSUE TITLE
SMB connection not authenticated

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iskylims#178]
### Description of the bug

When running Testing configuration, rises a SMB error.

### Relevant files

![image](https://github.com/BU-ISCIII/iskylims/assets/25959991/5df318b2-ee84-45ee-998e-66b5286e28ed)

### System information

iSkyLIMS version 2.3.1
Hardware: WS
OS: Ubuntu 20.04.4 LTS

**Comment by saramonzon** [comment]
Solved, there were some wrong credentials in the form
