### ISSUE TITLE
Upload files to service not working

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iskylims#188]
### Description of the bug

In Service request for massive sequencing experiments, when uploading files to the service request, they are not being uploaded.

Delete button should be next to the file to be deleted. Once deleted the file should disappear from the list of uploaded files.
![Screenshot from 2023-07-19 11-19-55](https://github.com/BU-ISCIII/iskylims/assets/25959991/c2f68654-d4d0-4642-bf42-74d33587f075)

**Comment by luissian** [comment]
It fails because in the installation script is missing the creation of documents/drylab/servicesRequestFiles.

**Comment by svarona** [comment]
Add `servicesRequestFiles` folder creation to install.sh @saramonzon
