### ISSUE TITLE
Problem when creating new sample type

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#19]
If you check all boxes in this form meaning al fields are mandatory, the option list field is set empty which makes the params visualization to fail. I think this if is not catching when the field is empty:

https://github.com/BU-ISCIII/iSkyLIMS_core/blob/9d3f4259736c7bff993f0e5e7b43e9c07ef2540a/models.py#L252-L255

**Comment by luissian** [comment]
Code was checking for NULL value instead of empty "".
It is now fixed
