### ISSUE TITLE
Create group per user and ability to add permissions

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#2]
Create an user interface to grant permissions to any user to see and manage their runs and services.
There will be a group per user and custom users will be added or removed by the User.
P.e bmartinezd_group
bmartinezd can add ggomezm to bmartinezd_group
bmartinezd can remove ggomezm to bmartinezd_group

**Comment by luissian** [comment]
This functionality it is already implemented and it is  included in django_utils version 1.2.3
