### ISSUE TITLE
Email settings fixes

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#20]
1. Remove settings.EMAIL_ISKYLIMS from settings.py and from all scripts where it is called like here:
https://github.com/BU-ISCIII/iSkyLIMS_drylab/blob/2809ddffd7929d94e90d224d2600c7c130008061/utils/handling_request_services.py#L682

2. Remove from email configuration form all text boxes, and only visualize parameters in settings.py
![image](https://user-images.githubusercontent.com/3480206/129897791-d162bad0-e5d5-49e3-80c8-588a092be96d.png)
Left only Email Address for iSkyLIMS  and email for testing.

Fix both wetlab and drylab.

**Comment by luissian** [comment]
The configuration email form is planned to be used for helping admin user to set the right values.
The information is collected from settings.py file. If the successful settings differs from the initial data, the admin user must apply the changes in settings.py file.

![image](https://user-images.githubusercontent.com/24755054/130050467-15d85cdd-4176-4524-b0a2-d772de7d376c.png)
On side panel help describes the way to proceed with changes
