### ISSUE TITLE
Add default molecule uses

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#21]
Add in the database by default this molecule uses:
- Whole Genome Sequencing
- RNA-Seq
- Exome-Seq
- Metagenomics
- Metagenetics
- miRNA-Seq
- Methyl-Seq
- hiC-Seq
- Amplicon-Seq
- RT-PCR (no massive)
- Sanger sequencing (no massive)

**Comment by luissian** [comment]
The table is populated with these data and loading tables files for new and upgrade installation are updated
