### ISSUE TITLE
Problem with Setting up the Test for iSKYLIMS via docker

### ISSUE THREAD

**Issue by YasirKusay** [BU-ISCIII/iskylims#218]
### Description of the bug

Hi,

I am following your guide on how to create a demo for this program via docker. At around step 15/24 of the setup, I get this error: " can't cd to iSkyLIMS_wetlab" along with a few errors. Could you assist me.
<img width="569" alt="Screen Shot 2023-08-20 at 8 06 10 am" src="https://github.com/BU-ISCIII/iskylims/assets/59812220/bbc987e8-4215-4290-bf18-c830f6869955">

**Comment by luissian** [comment]
Hi Yasir.
We are planned to release a new version of iSkyLIMS in the next coming weeks, where this issue is solved.
Please, wait a couple of weeks until we are ready to launch the new release

**Comment by saramonzon** [comment]
You can also try the code in the dev branch, and tell us if that works for you :)

**Comment by YasirKusay** [comment]
Thanks @saramonzon, it seems to be working now!

**Comment by saramonzon** [comment]
Great @YasirKusay ! We are still fixing things in the dev version, so please create an issue if you see any error !
