### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#22]
1. Add how to input option_list in all tables (comma separated)
2. Sample project menu - > help what this means, how you are going to add new possible fields.

**Comment by luissian** [comment]
Implemented help description for the fields to be used in the sample project.

![image](https://user-images.githubusercontent.com/24755054/130347932-ce2e058e-7694-48be-9ab1-3845dca4a1fc.png)
