### ISSUE TITLE
Crontab sets directly to error when runParameters is not found

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iskylims#224]
### Description of feature

This behaviour makes that runs are set to error when some transfer issues happen, the folder may exists but runParameter file is yet to be copied. 
We need to add a time counter so it waits 2-3 cron cycles before it sets the run to error so it can wait for the runParameters file to be copied if that's the case.

**Comment by luissian** [comment]
implemented this issue in PR 226
