### ISSUE TITLE
String field filled with numbers, gives error

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iskylims#237]
### Description of the bug

When filling samples table with numeric values, they are being recognized as numbers instead of strings:

[{'patient_core': <PatientCore: 323>, 'sample_name': '34', 'lab_request': 'ISCIII', 'sample_type': 'Blood', 'species': 'Human', 'sample_project': <SampleProjects: surveillance>, 'sample_entry_date': '2023-10-02 00:00:00', 'collection_sample_date': '2023-10-03 00:00:00', 'sample_location': '-80', 'only_recorded': True, 'user': 'admin', 'app_name': 'wetlab', 'sample_code_id': 'admin_34', 'unique_sample_id': 'AAA-0024', 'sample_state': 'Pre-Defined', 'success': True}, {'patient_core': 324, 'sample_name': 35, 'lab_request': 'ISCIII', 'sample_type': 'Blood', 'species': 'Human', 'sample_project': 'surveillance', 'sample_entry_date': '2023-10-03 00:00:00', 'collection_sample_date': '2023-10-04 00:00:00', 'sample_location': -79, 'only_recorded': True}, {'patient_core': 325, 'sample_name': 36, 'lab_request': 'ISCIII', 'sample_type': 'blood2', 'species': 'Human', 'sample_project': 'test-3', 'sample_entry_date': '2023-10-04 00:00:00', 'collection_sample_date': '2023-10-05 00:00:00', 'sample_location': -78, 'only_recorded': False}, {'patient_core': 326, 'sample_name': 37, 'lab_request': 'ISCIII', 'sample_type': 'blood2', 'species': 'Human', 'sample_project': 'test-3', 'sample_entry_date': '2023-10-05 00:00:00', 'collection_sample_date': '2023-10-06 00:00:00', 'sample_location': -77, 'only_recorded': False}, {'patient_core': 327, 'sample_name': 38, 'lab_request': 'ISCIII', 'sample_type': 'Blood', 'species': 'Human', 'sample_project': 'surveillance', 'sample_entry_date': '2023-10-06 00:00:00', 'collection_sample_date': '2023-10-07 00:00:00', 'sample_location': -76, 'only_recorded': True}]

**Comment by luissian** [comment]
fixed issue in PR #238
