### ISSUE TITLE
Move run stats to MainData

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#24]
![image](https://user-images.githubusercontent.com/3480206/129905070-bdd58336-3058-4011-8e3d-29d4751103bb.png)

**Comment by luissian** [comment]
Moved information to Main data tab and created new tab for unknown barcodes 
![image](https://user-images.githubusercontent.com/24755054/130108960-e6eddead-ee25-4e70-b065-4c388f1e08a7.png)
