### ISSUE TITLE
Searching by a non-recorded service ID ends in web error (dry_lab)

### ISSUE THREAD

**Issue by Daniel-VM** [BU-ISCIII/iskylims#241]
### Description of the bug

The web crashes when searching for a service ID and it is not recorded . "_TemplateDoesNotExist at /drylab/search-service_". 

Dry_lab > manage_service > search_service
 
![image](https://github.com/BU-ISCIII/iskylims/assets/69470278/3fd1c2c3-4a50-4730-a0f3-862d687a2cad)

**Comment by luissian** [comment]
Fixed at PR 239
