### ISSUE TITLE
Change table to jexcel

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#25]
![image](https://user-images.githubusercontent.com/3480206/129908510-8b057102-18df-4dda-b6d8-a116c1437a24.png)

**Comment by luissian** [comment]
Changed the html table to jexcel
![image](https://user-images.githubusercontent.com/24755054/130315591-ffcd60e9-afbf-4e55-9c1a-f2d94e80c324.png)
