### ISSUE TITLE
Confirmation email after resolution: wrong text and email 

### ISSUE THREAD

**Issue by juanledesma78** [BU-ISCIII/iskylims#261]
### Description of the bug

This has happened several times to me doing services for different labs. 

As soon as the resolution is created the confirmation email is sent to bioifnormatica@isciii.es, the reseracher and also to myself.
  
It may be something related to my time working as a researcher in the Arboviruses lab before joining the BU, but it is worth checking it. In addition the text of the email is confusing 

```
Dear juan.ledesma
A new resolution has been added for your service:  SRVCNM1068.
Your service has been accepted
because it does not fullfil our requirements or is not in our services portfolio.
If you have any question please contact us.
Kind regards
BU-ISCIII
```
Although the service has been successfully accepted the email states "because it does not fullfil our requirements or is not in our services portfolio", which should not.

**Comment by luissian** [comment]
Fixed in commit 333aa23d
