### ISSUE TITLE
bu-isciii tools `--dev` flag will prevent email notifications during testing phases and may require ajustment in iSkylims

### ISSUE THREAD

**Issue by Daniel-VM** [BU-ISCIII/iSkyLIMS#268]
### Description of feature

The upcoming feature for the bu-isciii tools will introduce a --dev option to prevent sending email notifications to iSkylims users during testing phases. This implementation may require adjustments in iSkylims.

Related: [buisciii-tools#262](https://github.com/BU-ISCIII/buisciii-tools/issues/262)

**Comment by luissian** [comment]
You should use the iSkyLIMS that is in development a not the one in production for your testing.
I recommend you that when using --dev parameter change the IP address of iSkyLIMS to use the one in develop.

**Comment by Daniel-VM** [comment]
Ok. Thanks @luissian !
