### ISSUE TITLE
ERROR: Settings' object has no attribute 'EMAIL_ISKYLIMS'

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#27]
![image](https://user-images.githubusercontent.com/76442429/130480462-a52b8438-3f12-43a4-8ac6-4fb5eedb4793.png)

**Comment by luissian** [comment]
Replaced the EMAIL_ISKILIMS value by "EMAIL_FOR_NOTIFICATIONS"
