### ISSUE TITLE
no signature found for builtin <built-in method center of str object at 0x7fb2ca9feab0>

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#28]
![image](https://user-images.githubusercontent.com/76442429/130482746-82ff107a-e039-4ec5-a69b-aab8f4d8b2b2.png)

**Comment by luissian** [comment]
The PDF generated file will be removed, according to the new philosophy of each user creates his own report (using his own script) by requesting the information required via API.
Detailed information is inside the issue 33
