### ISSUE TITLE
Error in Analyzed Samples plot from Statistics by service requested 

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iSkyLIMS#280]
### Description of the bug

In Drylab > Manage Service > Statistics by Service Requested
After performing a search, the plot Analyzed Samples shows 100% of Only Recorded Samples, when it's not true:
![image](https://github.com/user-attachments/assets/1b16f483-76c6-45d6-a94c-45186af509b4)

**Comment by luissian** [comment]
solved in commit  1db4a19
