### ISSUE TITLE
Rename some names in tabs and plots

### ISSUE THREAD

**Issue by svarona** [BU-ISCIII/iSkyLIMS#282]
### Description of the bug

Requested Services ➜ Service requests
Requested From ➜ Requested by
Analyzed Samples ➜ Sample analysis
Analyzed Samples Table ➜ Sample analysis table
Services Status ➜ Service status
Status of Requested Services ➜ Service request status
Requested Services per user ➜ Service Requests by User
Requested Services per center ➜ Service Requests by Center
Services per classification area ➜ Service Requests by Classification Area
Service statistics per center ➜ Service Request Statistics by Center
Services Statistics per classification area ➜ Service Request Statistics by Classification Area
Analyzed Samples per user ➜ Analyzed Samples by User
Analyzed Samples ➜ Sample Analysis
Analyzed Samples from sequenced in runs ➜ Analyzed Samples from Sequencing Runs
Analyzed Samples grouped in projects ➜ Analyzed Samples by Project

Credit @saramonzon

**Comment by luissian** [comment]
Changes done:
- [x] Requested Services ➜ Service requests
- [x] Requested From ➜ Requested by
- [x] Analyzed Samples ➜ Sample analysis
- [x] Analyzed Samples Table ➜ Sample analysis table
- [x] Services Status ➜ Service status
- [x] Status of Requested Services ➜ Service request status
- [x] Requested Services per user ➜ Service Requests by User
- [x] Requested Services per center ➜ Service Requests by Center
- [x] Services per classification area ➜ Service Requests by Classification Area
- [x] Service statistics per center ➜ Service Request Statistics by Center
- [x] Services Statistics per classification area ➜ Service Request Statistics by Classification Area
- [x] Analyzed Samples per user ➜ Analyzed Samples by User
- [x] Analyzed Samples ➜ Sample Analysis
- [x] Analyzed Samples from sequenced in runs ➜ Analyzed Samples from Sequencing Runs
- [x] Analyzed Samples grouped in projects ➜ Analyzed Samples by Project

Solved in commit 73e4a28
