### ISSUE TITLE
AttributeError at /wetlab/searchSample/

### ISSUE THREAD

**Issue by pirega** [BU-ISCIII/iSkyLIMS#40]
![imagen](https://user-images.githubusercontent.com/7210409/135108743-46a1520a-959a-4b16-9ac2-520775896096.png)

**Comment by pirega** [comment]
Estamos intentando buscar una muestra que existe y está cargada toda la información, pero da ese error de búsqueda.

**Comment by luissian** [comment]
Fixed.
get_info_for_searching function does not exist for "SamplesInProjects" object. The right one is "get_basic_info()"
