### ISSUE TITLE
Alta de paciente desde Clinic

### ISSUE THREAD

**Issue by pirega** [BU-ISCIII/iSkyLIMS#42]
![imagen](https://user-images.githubusercontent.com/7210409/135280705-6c7f51ff-5b9b-48c8-a1df-3f20d2d1ddb7.png)

**Comment by pnatividad-incliva** [comment]
![image](https://user-images.githubusercontent.com/76442429/135296792-949e06c0-a665-46af-9476-e15604c8485a.png)
It's not ok, because 2 fields not display
