### ISSUE TITLE
Problema al cargar la sample sheet para asignar indices

### ISSUE THREAD

**Issue by pirega** [BU-ISCIII/iSkyLIMS#44]
Tras dar de alta las muestras del primer run me aparece esto al cargar la samplesheet
![imagen](https://user-images.githubusercontent.com/7210409/135593940-62ca60a5-fe61-474c-844e-93936b230010.png)

Pero las muestras si que están
![imagen](https://user-images.githubusercontent.com/7210409/135594263-63a783b4-f32b-4b4b-a899-ddbd76fbaa2f.png)

y da igual que lo haga con ONC1-0001, que con ONC1-ONC1-0001 en la samplesheet que cargo, no me reconoce ninguna
![imagen](https://user-images.githubusercontent.com/7210409/135594374-e6d52237-ad70-4067-aa87-c629cdcc74dc.png)

**Comment by luissian** [comment]
The default separation character between protocol and sample name was "_" (underscore) . Now a new configuration item (PROTOCOL_SEPARATION_IN_SAMPLE_SHEET) is created in database to allow that each lab defines its own separation character.
