### ISSUE TITLE
Graphic comparations:  boxandwhisker2d doesn´t work fine when there are less than 3 projects

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#45]
![image](https://user-images.githubusercontent.com/76442429/136693528-956f5e0b-a5fc-4cdd-b01a-1465b734ef95.png)
![image](https://user-images.githubusercontent.com/76442429/136693550-1bdc0564-e5c3-4f4b-9392-899012faabb3.png)

**Comment by luissian** [comment]
Bug corrected
