### ISSUE TITLE
No es posible reutilizar una librería en otro pool

### ISSUE THREAD

**Issue by pirega** [BU-ISCIII/iSkyLIMS#48]
Al intentar reutilizar una "Library_Preparation" en otro pool me dice lo siguiente:
![imagen](https://user-images.githubusercontent.com/7210409/140037330-f8bde710-57b9-4cd7-a006-39f81d5e07c6.png)

Partiríamos de este punto:
![imagen](https://user-images.githubusercontent.com/7210409/140037384-5938eeab-d4db-44bf-bdff-70b7dc87e79a.png)

**Comment by luissian** [comment]
Faltan definir más estados en  la tabla de StateForLibraryPreparation.

![image](https://user-images.githubusercontent.com/24755054/140050008-d3c4ceaf-ec35-474b-a2ca-89768c942910.png)

Puedes comprobarlo con el admin?

**Comment by pirega** [comment]
Añadido ;)

**Comment by pirega** [comment]
Sigue saliendo error
![imagen](https://user-images.githubusercontent.com/7210409/140050965-ec817f78-07d1-46fa-be74-ab35135fdcd1.png)

**Comment by luissian** [comment]
si, es lo que te he dicho por email. hay que hacer un pull de github para corregir este error que te ha salido
