### ISSUE TITLE
Install script fails during database structure creation

### ISSUE THREAD

**Issue by Fabian-RY** [BU-ISCIII/iSkyLIMS#50]
Yesterday, on 22th november I tried to install iSkyLims on a fresh Ubuntu 20.04 with the install.sh script. However, the installation failed while trying to create the database structure. I ran the installation script following the docs. This was the error, in which python found a non-initialized variable in settings.py

![imagen](https://user-images.githubusercontent.com/57529812/143002873-28082078-2f7d-4d17-898a-a90c9022d2af.png)

Given that it was the data about the email server that i specified in the conf file of the install script, i checked if the data was updated to settings.py correctly, and it wasn't. In particular, the password file of the email server and the use of tls of the same server were updated with localhost, which it doesn't make sense in this field. The script failed because the value of the EMAIL_USE_TLS is defined as variable. This variable was never initialized, therefore giving the error. 

![imagen](https://user-images.githubusercontent.com/57529812/143005956-21427a54-ecb7-4ce0-8b9b-74c4318cc1ae.png)

The dummy values are substituted by a chain of sed commands, in which the first one searches for emailhost and substitutes them all... while the other ones also include emailhost as part of the word to substitute. The first sed will change all emailhost it founds... making all the others sed commands (such as the one which changes emailhostpass or emailhosttls ) not to found the correct pattern and thus not giving the correct data. 

![imagen](https://user-images.githubusercontent.com/57529812/143007815-e01132b6-a43f-4d39-bb23-50106f1d19d1.png)

I added an extra sed command that puts a False value to the EMAIL_USE_TLS variable instead of the current value and then the installation ended successfully. iSkyLims can be accessed through localhost in the web browser. The database information it seemed to be correct, and only the email data is affected, as iSkyLIMS worked after solving this problem: registration of the admin user worked correctly and it's able to log in. 

The problem is, in fact, that the first sed changes all instances of emailhost, while the next seek for emailhostpass and similar constructions that are changed after the first sed command is run.

**Comment by luissian** [comment]
Thanks for helping us to debug the script.
I will create a hot fix to solve this issue.

**Comment by luissian** [comment]
Corrected in  hotfix 2.0.1
