### ISSUE TITLE
Drylab--> Requesting Services Application loses the menu

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#52]
![image](https://user-images.githubusercontent.com/76442429/143482791-7fdf6ca1-e834-436c-9d19-366169ced403.png)

**Comment by pnatividad-incliva** [comment]
the menu appears but cannot be displayed

**Comment by luissian** [comment]
Unable to reproduce the error.
Issue will reopen if provided the way to reproduce the faulty situation
