### ISSUE TITLE
'Resolution' object has no attribute 'servicePipelines'

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#53]
![image](https://user-images.githubusercontent.com/76442429/143941773-604cda5e-be9d-463b-b3e5-2410e5a09ba5.png)
![image](https://user-images.githubusercontent.com/76442429/143941817-bdd9b201-737e-41b6-a834-db6995aca67b.png)

Se incluye el campo 'servicePipelines' en ResolutionSerializer, pero este campo no existe en el modelo Resolution.

![image](https://user-images.githubusercontent.com/76442429/143941988-7c137ad3-2a03-41a2-91f7-79ebd1731a73.png)

**Comment by pnatividad-incliva** [comment]
![image](https://user-images.githubusercontent.com/76442429/144091317-d09ff9ba-9d02-49f3-b776-a167d9dd2032.png)
 LO he solucionado cambiando en la clase ResolutionSerializer servicePipelines por resolutionPipelines y ya funciona ok.

**Comment by luissian** [comment]
Thanks Pilar for solving the issue.
Corrected in the hotfix 2.0.1
