### ISSUE TITLE
API DRYLAB, drylab/api/updateResolution  doesn't work fine

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#55]
![image](https://user-images.githubusercontent.com/76442429/148806215-e59bb014-c8d6-4827-8faa-01da251aaf49.png)

**Comment by pnatividad-incliva** [comment]
Change request.data to request.query_params for it to work properly.

**Comment by luissian** [comment]
Thanks for debugging  the issue.
Issue is solved as part of the hotfix 2.0.1.
Line for checking the configuration email is removed as the checking now is querying database
