### ISSUE TITLE
Service view

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#58]
Adjust table size in `Sequencing Samples requested in service` panel.

**Comment by luissian** [comment]
Sample table is resize to use total width and resize height . Code updated in  commit aa93b42ce28aec26b3e6903f08b8ffc4d6aea3fb

![image](https://user-images.githubusercontent.com/24755054/154150422-a04acc8d-4f7f-477f-9944-3af195f6792e.png)
