### ISSUE TITLE
Apache2 configuration - for those who need it

### ISSUE THREAD

**Issue by AKWB** [BU-ISCIII/iSkyLIMS#6]
**add in /etc/apache2/apache2.conf**
Include /etc/apache2/httpd.conf

**then create /etc/apache2/httpd.conf with content accoring to wiki-page https://github.com/BU-ISCIII/iSkyLIMS/wiki/Apache**

**replace everywhere** 
Satisfy Any
Allow from all

**by**
Require all granted

**Comment by saramonzon** [comment]
Thanks a lot! We will add it to the wiki!
