### ISSUE TITLE
Bug in my pending task tab in drylab module queued resolution are shown in both queued and in progress

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#64]
In the my pending tasks tab queued resolution are shown in both queued and in progress table.
https://github.com/BU-ISCIII/iSkyLIMS/blob/0b45fe19caa3ba4d3db4b33e7e6a5e9850dbea25/iSkyLIMS_drylab/templates/iSkyLIMS_drylab/pendingServices.html#L270-L277

Line 270 should iterate over user_pending_services.in_progress

**Comment by luissian** [comment]
Fixed in commit 9ce198222cc80a298b51734eb296701d08b4d48d
