### ISSUE TITLE
Service name in Requesting Services Application

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#70]
In Requesting Services Application, when adding a new service, automatically the service name is constructed as the constant defined in drylab_config.py (ABBREVIATION_USED_FOR_SERVICE_REQUEST = 'SRV') + the center to which the user belongs + the consecutive service number that corresponds. 
This nomenclature is not useful to us, so we would like it to be parameterizable, in our case only with what we assign in the constant ABBREVIATION_USED_USED_FOR_SERVICE_REQUEST + the consecutive service number.

**Comment by luissian** [comment]
USER_CENTER_USED_FOR_NAMING_SERVICE and  ABBREVIATION_USED_FOR_SERVICE_REQUEST, configured on database( config_settings drylab) will be  defined

**Comment by luissian** [comment]
Implented in commit 8612fbe621a17b69147fdd05adf4d4685fe87e45
It is required to add manually the following row in iSkyLIMS_drylab-config_setting table using django admin
-  USER_CENTER_USED_FOR_NAMING_SERVICE
- ABBREVIATION_USED_FOR_SERVICE_REQUEST
