### ISSUE TITLE
Allow label changes in iSkyLIMS

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#71]
Allow label changes in iSkyLIMS, which could be stored in a database and parameterized instead of putting them directly into the code, like the labels that appear in iSkyLIMS :
- Massive Sequencing Application 
- Requesting Services Application

Possibility of changing also the name of the entity (BU-ISCIII) that can be changed by ours (we do not refer to the BU-ISCIII that appears in the footer, that should appear).

**Comment by luissian** [comment]
For main apps the label that appears in the main pages can be changed in settings.py file.
Replace the text in the list for the ones that you want to display in the menu
APPS_NAMES = [ ['iSkyLIMS_clinic', 'Clinic'],
    ['iSkyLIMS_wetlab', 'Masive Sequencing'],
    ['iSkyLIMS_drylab','Requesting Services']
]
Name of your organization can be set , by changing (using django admin utility)  the value of ORGANIZATION_NAME . This change must be set for wetlab and drylab on the ConfigSettings table.
