### ISSUE TITLE
Annual Report

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#72]
In an early version of iSkyLIMS there was a menu option in the Massive Sequencing Application to view graphical comparisons of runs sequenced over a year. It has disappeared, and we would like to see it displayed again because we see it as very useful.
(wetlab/AnnualReport).
Annual reports generate graphics and data for all runs that have been started on the selected year.

**Comment by luissian** [comment]
The Reports are restored back, in the next coming release 2.1.0.
The changed was done in commit 0eb0fcd80ee66e98c089dce3612ecee3c06290ea
