### ISSUE TITLE
control: the name of the sample do not contain the underscore (_)

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iskylims#73]
When loading the SampleSheet or registering samples in iSkyLIMS, it should check that the names of the samples do not contain the underscore (_), as they then give errors when analyzed in the pipelines used.

**Comment by luissian** [comment]
Added on version 3.1.0 which include a configuration parameter to allow or not the underscore character on sample
- ALLOW_SAMPLE_NAMES_WITH_UNDERSCORE

By default is set to FALSE

**Comment by luissian** [comment]
Is implemented on 3.1.0, however the new issue #272 will overwrite the code for this issue
