### ISSUE TITLE
DRYLAB: include a table for services status

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#79]
In DRYLAB, the status of the service is configured directly from a tuple defined in the *model.py* file of the iSkyLIMS_drylab application. In our case we would like to change the descriptions of the service, and we have done it from here, but then in some html screens the state that appears is the id, and it does not correspond in our case with the description we want. For example, we want the rejected status to be Cancelled, or delivered to be Finished. It would be nice if the status was in a table in the database.

**Comment by luissian** [comment]
New class called ServiceState contains now the value for handling internally as well a field to modify the value to the one that will display in the application.
Additional to this field, there are 2 new:
- description. Display a full text with more detailed information about the state.
- show_in_stats. Boolean value to decided in the state will be included in graphic statistics. This field will remove the existing hardcode (selecting the states) for displaying stats.

The existing value for service state based on the fixed choices, will remain for table migration purpose, but it will removed from release 2.4.0 or later .

Code is updated to use this new "ServiceState" class.

**Comment by luissian** [comment]
Implemented in #136
