### ISSUE TITLE
Re-upload of a corrected sample sheet does not work

### ISSUE THREAD

**Issue by AKWB** [BU-ISCIII/iSkyLIMS#8]
I corrected my sample sheet --> user in the description field
If I try to upload the corrected sheet, I keep on getting the same error message as before (Researcher XY not in Database). Is there something like a cache? Or do I need to do something?

Greets

**Comment by AKWB** [comment]
stop...I forgot to change it in the sample data section...

**Comment by AKWB** [comment]
![image](https://user-images.githubusercontent.com/23099946/52711628-8d11de80-2f92-11e9-91de-99b195b2c4d5.png)


??? I do not have a folder getSampleSheet

**Comment by AKWB** [comment]
Whatever happened, I went on "Try Again" and it works

**Comment by saramonzon** [comment]
glad it works! Sometimes weird things happen!
