### ISSUE TITLE
change identity of the company installing iSkyLIMS

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#80]
It should be possible to configure the application with the identity of the company installing iSkyLIMS. On many screens BU-ISCIII appears and we would like to be able to change it to our initials. I have changed the index.html templates for this, but it would be nice if this text could be configured.

**Comment by luissian** [comment]
A new configuration parameter  is defined in database to write your organization name.
To implement this change require to define manually the parameter  "ORGANIZATION_NAME"  for clinic, wetlab and drylab using django admin 

Changes were done on commits 131d05235deafd9094da7e7198c5516df373e158
64ab409a0ec0739a26525268ec94e3d393ea2b22
