### ISSUE TITLE
 Statistics/Projects per researcher does not work properly.

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#84]
in wetlab in the option Statistics/Projects per researcher does not work properly. There is a bug in the code of the function *get_researcher_statistics*. 
# over write the user name with the full user id
    researcher_statistics['researcher_name'] = user_objs[0].username 
must be:
 researcher_statistics['researcher_name'] = user_objs[0].id

The comment is in but no id is used. With this change it works ok.

**Comment by pnatividad-incliva** [comment]
My solution is necessary, but the filter 

     sample_objs= sample_objs.filter(runProcess_id__state__runStateName__range=(start_date, end_date))
  
does not retrieve any data, and it does exist.

**Comment by pnatividad-incliva** [comment]
This change makes it work fine:
 
if SamplesInProject.objects.filter(user_id = user_objs[0].id).exists():
        sample_objs = SamplesInProject.objects.filter(user_id = user_objs[0].id).order_by('runProcess_id')

**Comment by luissian** [comment]
Thanks for your help.
I will update the code according your suggestion, in the next release

**Comment by luissian** [comment]
Fixed bug when statistics are filtered by date, by changing :
 sample_objs= sample_objs.filter(runProcess_id__state__runStateName__range=(start_date, end_date))
to :
sample_objs= sample_objs.filter(runProcess_id__run_date__range=(start_date, end_date))

Change done on commit 4d827d245a3ccf34656defa8bc78048132738b3d
Pending for confirmation on testing before closing issue.
