### ISSUE TITLE
available services

### ISSUE THREAD

**Issue by AKWB** [BU-ISCIII/iSkyLIMS#9]
I added a lot of services in the admin panel - drylab. But in the "requesting service" sites I only see AvailableServices *

How do I get them visible? Is it a user thing? And how do I "sort" those services to "request consultation",...?

I did not find anything in your wiki.

Greets

**Comment by saramonzon** [comment]
Hi!
We have to add a lot of info in the wiki...thanks for the debugging.
You have to create three available services named:
- Genomic Data Analysis
- Bioinformatics consulting and training
- User support

Then add all the services you want and classify them inside one of these three categories. In admin you can drag and drop the services one inside another, this way you make a "tree" of categories that will be shown in the form.

Hope I have explained myself!
An example of our configuration:
![available_services1](https://user-images.githubusercontent.com/3480206/52726369-5dbf9980-2fb3-11e9-84fc-face053ae0b3.png)
