### ISSUE TITLE
Add scroll in excel form for project metadata

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS#96]
![image](https://user-images.githubusercontent.com/3480206/161956956-a8aad0ef-e50f-40d7-8330-9e9518fc059f.png)

**Comment by saramonzon** [comment]
Also fix it in the sample display!
![image](https://user-images.githubusercontent.com/3480206/161957199-a84dd810-1be4-4bcf-926b-6f2913384c18.png)

**Comment by luissian** [comment]
Issue is corrected in commit 4cbce8c23ffca45027fa86ba006facaad21f1a20
