### ISSUE TITLE
If the run created in iSkyLIMS_wetlab already exists, the projects are duplicated when the run is loaded.

### ISSUE THREAD

**Issue by pnatividad-incliva** [BU-ISCIII/iSkyLIMS#99]
In the file  **handling_crontab_bcl2fastq.py** defines the function  **process_and_store_raw_demux_project_data** , which reads the samplesheet projects and, if they do not exist, registers them. In some cases the project already exists, and this procedure duplicates them. To solve it the code has been modified:

for project in parsed_data.keys():
        if project == 'TopUnknownBarcodes'  or project == 'all' or project == 'default':
            continue
        if not project in project_list:
            # create project and link to the run
            # check if project exists yet
            **if not Projects.objects.filter(projectName__exact = project).exists():
               new_project_obj = Projects.objects.create_new_empty_project({'user_id':None, 'projectName':project})
            else:
               new_project_obj =  Projects.objects.filter(projectName__exact = project).last()**
            new_project_obj.runProcess.add(run_process_obj)
            string_message = experiment_name +  ' : Created  project name ' + project + 'Because it was not store'
            logging_warnings(string_message, True)

**Comment by luissian** [comment]
Issue solved in commit f853945a4b932bd26d376a85b09899c261836f8b
